version: "3.8"
# Useful links
# localstack overview https://github.com/localstack/localstack#overview
# https://dev.to/goodidea/how-to-fake-aws-locally-with-localstack-27me
# https://www.stevejgordon.co.uk/running-aws-s3-simple-storage-service-using-docker-for-net-core-developers
services:
  localstack-s3:
    image: localstack/localstack:latest
    container_name: localstack-s3

    # List of all configurations that can be passed as environment variables
    # https://github.com/localstack/localstack#configurations
    environment:
     - SERVICES=s3, ses # Enabled services 
     # https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints
     - DEFAULT_REGION=ap-southeast-1 # Asia Pacific (Singapore)
     - DATA_DIR=/localstack-data/s3
    ports:
     - "4566:4566" # All services' ports
     - "8000:8080" # LocalStack web UI port
    volumes:
        # Map host's directory to a container's directory
      - ./localstack-data/s3:/localstack-data/s3

# To test a service with AWS CLI
# Override a default value 
# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/index.html
# aws --endpoint-url=http://localhost:4566 --region ap-southeast-1 s3 ls
# mock SES https://github.com/codesanook/sese
