version: "3.8"
# Useful links
# localstack overview https://github.com/localstack/localstack#overview
# https://blog.jcore.com/2020/04/running-aws-locally-with-localstack/
services:
  localstack-s3:
    image: localstack/localstack:latest
    container_name: localstack-s3

    # List of all configurations that can be passed as environment variables
    # https://github.com/localstack/localstack#configurations
    environment:
     - SERVICES=s3 # Enable only AWS S3 services
     # https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints
     - DEFAULT_REGION=ap-southeast-1 # Asia Pacific (Singapore)
     - DATA_DIR=/localstack-data
    ports:
     - "4563-4599:4563-4599" # Ports of the different services
     - "8000:8080" # LocalStack web UI port
    volumes:
        # Map host's directory to a container's directory
      - ./localstack-data:/localstack-data

# To test a service with AWS CLI
# Override a service URL default value 
# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/index.html

# Create a profile 
# aws configure --profile localstack

# Create a bucket
# aws s3api create-bucket --bucket bucket-name --endpoint-url http://localhost:4572 --profile localstack

# List all buckets
# aws s3api list-bucket --endpoint-url http://localhost:4572 --profile localstack
